In [1]:
import tensorflow as tf
import numpy as np

In [2]:
(x_train,  y_train)  , (x_test , y_test) =  tf.keras.datasets.imdb.load_data(num_words=10000)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
x_train.shape

(25000,)

In [4]:
"" "unknown"

'unknown'

In [5]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
voc

NameError: name 'voc' is not defined

In [7]:
voc = tf.keras.datasets.imdb.get_word_index()

voc =  { word : index+3    for word  , index  in voc.items()}

reverse_voc =  { v:k   for k , v in voc.items()}
reverse_voc

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


{34704: 'fawn',
 52009: 'tsukino',
 52010: 'nunnery',
 16819: 'sonja',
 63954: 'vani',
 1411: 'woods',
 16118: 'spiders',
 2348: 'hanging',
 2292: 'woody',
 52011: 'trawling',
 52012: "hold's",
 11310: 'comically',
 40833: 'localized',
 30571: 'disobeying',
 52013: "'royale",
 40834: "harpo's",
 52014: 'canet',
 19316: 'aileen',
 52015: 'acurately',
 52016: "diplomat's",
 25245: 'rickman',
 6749: 'arranged',
 52017: 'rumbustious',
 52018: 'familiarness',
 52019: "spider'",
 68807: 'hahahah',
 52020: "wood'",
 40836: 'transvestism',
 34705: "hangin'",
 2341: 'bringing',
 40837: 'seamier',
 34706: 'wooded',
 52021: 'bravora',
 16820: 'grueling',
 1639: 'wooden',
 16821: 'wednesday',
 52022: "'prix",
 34707: 'altagracia',
 52023: 'circuitry',
 11588: 'crotch',
 57769: 'busybody',
 52024: "tart'n'tangy",
 14132: 'burgade',
 52026: 'thrace',
 11041: "tom's",
 52028: 'snuggles',
 29117: 'francesco',
 52030: 'complainers',
 52128: 'templarios',
 40838: '272',
 52031: '273',
 52133: 'zaniacs',

In [8]:
x_train[2]

[1,
 14,
 47,
 8,
 30,
 31,
 7,
 4,
 249,
 108,
 7,
 4,
 5974,
 54,
 61,
 369,
 13,
 71,
 149,
 14,
 22,
 112,
 4,
 2401,
 311,
 12,
 16,
 3711,
 33,
 75,
 43,
 1829,
 296,
 4,
 86,
 320,
 35,
 534,
 19,
 263,
 4821,
 1301,
 4,
 1873,
 33,
 89,
 78,
 12,
 66,
 16,
 4,
 360,
 7,
 4,
 58,
 316,
 334,
 11,
 4,
 1716,
 43,
 645,
 662,
 8,
 257,
 85,
 1200,
 42,
 1228,
 2578,
 83,
 68,
 3912,
 15,
 36,
 165,
 1539,
 278,
 36,
 69,
 2,
 780,
 8,
 106,
 14,
 6905,
 1338,
 18,
 6,
 22,
 12,
 215,
 28,
 610,
 40,
 6,
 87,
 326,
 23,
 2300,
 21,
 23,
 22,
 12,
 272,
 40,
 57,
 31,
 11,
 4,
 22,
 47,
 6,
 2307,
 51,
 9,
 170,
 23,
 595,
 116,
 595,
 1352,
 13,
 191,
 79,
 638,
 89,
 2,
 14,
 9,
 8,
 106,
 607,
 624,
 35,
 534,
 6,
 227,
 7,
 129,
 113]

In [9]:
decoded_r = "".join( reverse_voc.get(i , "?")+" "  for i in x_train[0])
print(decoded_r)

? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you thi

In [10]:
len(decoded_r.split())

218

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

x_train_pad  =  pad_sequences(x_train , maxlen=200 , padding="post" , truncating="post")
x_test_pad =  pad_sequences(x_test  , maxlen = 200  , padding = "post")

In [12]:
len(x_train[0])

218

In [13]:
x_train_pad[11]

array([   1,   54,   13, 1610,   14,   20,   13,   69,   55,  364, 1398,
         21,   54,   13,  219,   12,   13, 1706,   15,    4,   20,   16,
        329,    6,  176,  329,   74,   51,   13,  873,    4,  156,   71,
         78,    4, 7412,  322,   16,   31,    7,    4,  249,    4,   65,
         16,   38,  379,   12,  100,  157,   18,    6,  910,   20,  549,
         18,    4, 1496,   21,   14,   31,    9,   24,    6,  212,   12,
          9,    6, 1322,  991,    7, 3002,    4,  425,    9,   73, 2218,
        549,   18,   31,  155,   36,  100,  763,  379,   20,  103,  351,
       5308,   13,  202,   12, 2241,    5,    6,  320,   46,    7,  457,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [14]:
len(x_train_pad) /32

781.25

In [15]:
32  , 200 , 128

(32, 200, 128)

In [17]:
from keras.layers  import Embedding  , Dense  , SimpleRNN  , LSTM

In [25]:
voc_size =  10000

In [80]:
model  =  tf.keras.Sequential([

                               Embedding(10000 , 128 ,mask_zero=True ) ,
                               SimpleRNN(128 , return_sequences=True , activation="tanh") ,
                               SimpleRNN(64 , return_sequences=False , activation="tanh") ,
                               Dense(1 , activation="sigmoid")
]

)

In [19]:
model  =  tf.keras.Sequential([

                               Embedding(10000 , 128 ,mask_zero=True ) ,
                               LSTM(128 , return_sequences=True , activation="tanh") ,
                               LSTM(64 , return_sequences=False , activation="tanh"),
                               Dense(1 , activation="sigmoid")
]

)

In [89]:
128*128 +16384+128

32896

In [92]:
128*128 + 128*128 +128

32896

In [ ]:
# d*h + h*h +h

In [91]:
128*64 + 64*64+64

12352

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [74]:
model.trainable = False

In [84]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 200, 128)       │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 200, 128)       │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_5 (SimpleRNN)        │ (None, 64)             │        12,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,975,941 (15.17 MB)

 Trainable params: 1,325,313 (5.06 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,650,628 (10.11 MB)

In [21]:
model.compile(optimizer="adam" , loss =  "binary_crossentropy" , metrics =["accuracy"])

In [22]:
model.fit(x_train_pad , y_train , epochs=10 , batch_size=32 , validation_data=(x_test_pad , y_test))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 27s 29ms/step - accuracy: 0.6211 - loss: 0.6405 - val_accuracy: 0.5740 - val_loss: 0.7250
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 29ms/step - accuracy: 0.7321 - loss: 0.5378 - val_accuracy: 0.8234 - val_loss: 0.4031
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 22s 28ms/step - accuracy: 0.8551 - loss: 0.3435 - val_accuracy: 0.8343 - val_loss: 0.3646
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 26ms/step - accuracy: 0.8910 - loss: 0.2769 - val_accuracy: 0.8682 - val_loss: 0.3224
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 22s 28ms/step - accuracy: 0.9087 - loss: 0.2368 - val_accuracy: 0.8641 - val_loss: 0.3261
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - accuracy: 0.9264 - loss: 0.1985 - val_accuracy: 0.8588 - val_loss: 0.3450
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 26ms/step - accuracy: 0.9379 - loss: 0.1716 - val_accuracy: 0.8525 - val_loss: 0.3849
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 22s 28ms/step - accuracy: 0.9480 - loss: 0.1469 - 

In [23]:
def encode_review(text  ,word_index):
      words  =  text.lower().split()
      seq =  []
      for word in words :
        seq.append(word_index.get(word , 2))
      return seq

In [33]:
review  = encode_review("i love this terrible  amazing movie" , voc)
review  =  pad_sequences([review] , maxlen=200 , padding="post")

In [34]:
review.shape

(1, 200)

In [35]:
pred = model(review)

In [36]:
pred

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.14522289]], dtype=float32)>

In [37]:
if pred[0][0] >= 0.5 :
  print("postive")
else :
  print("negative")


negative


In [38]:
x_test[0]

[1,
 591,
 202,
 14,
 31,
 6,
 717,
 10,
 10,
 2,
 2,
 5,
 4,
 360,
 7,
 4,
 177,
 5760,
 394,
 354,
 4,
 123,
 9,
 1035,
 1035,
 1035,
 10,
 10,
 13,
 92,
 124,
 89,
 488,
 7944,
 100,
 28,
 1668,
 14,
 31,
 23,
 27,
 7479,
 29,
 220,
 468,
 8,
 124,
 14,
 286,
 170,
 8,
 157,
 46,
 5,
 27,
 239,
 16,
 179,
 2,
 38,
 32,
 25,
 7944,
 451,
 202,
 14,
 6,
 717]